[package]
edition.workspace    = true
name                 = "testing_ground"
repository.workspace = true
version              = "0.0.0"

[dependencies]
csv        = "1.3.0"
serde      = { version = "1.0.208", features = ["derive"] }
serde_yaml = "0.9.34"
