[package]
edition.workspace    = true
name                 = "black_hat_rust"
repository.workspace = true
version              = "0.0.0"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
hex  = "0.4.3"
sha1 = "0.10.6"
